service: config

plugins:
  - serverless-s3-sync
  - serverless-iam-roles-per-function

custom:
  bucketName: config-ujl2de7-${self:provider.stage}

  s3Sync:
    - bucketName: ${self:custom.bucketName}
      localDir: build

  stage: ${self:provider.stage}

provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-1
  stage: ${opt:stage, 'dev'}
  logRetentionInDays: 1
  memorySize: 1536

functions:
  getConfig:
    handler: src/index.default
    environment:
      BUCKET_NAME: ${self:custom.bucketName}
    events:
      - http:
          path: config
          method: get
    iamRoleStatements:
      - Effect: Allow       
        Action:
          - s3:GetObject
          - s3:ListBucket     
        Resource:
          Fn::GetAtt:
            - ConfigBucket
            - Arn

resources:
  Resources:
    ConfigBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.bucketName}